### ISSUE TITLE
ARM MacOS is not supported by Trinity

### ISSUE THREAD

**Issue by MGPelaar** [motivewc/wowpatch#4]
I could not sign in to the server, because the ARM MacOS is not supported by Trinity Core. How did you modify the Trinity Core to be able to log in with mac?

`[Battlenet::LogonRequest] [x.x.x.x:xxxx] attempted to log in from an unsupported platform (using MacA)!
[x.x.x.x:xxxx] Client called server method AuthenticationService.Logon() bgs.protocol.NoData{  } status 79.
[x.x.x.x:xxxx] Server called client method ConnectionService.ForceDisconnect(bgs.protocol.connection.v1.DisconnectNotification{ error_code: 0 })
[x.x.x.x:xxxx] Client called server method ConnectionService.RequestDisconnect(bgs.protocol.connection.v1.DisconnectRequest{ error_code: 0 }).`

**Comment by MGPelaar** [comment]
Anyone having this issue can use this pull request from the author of this tool, to make the server compatible: [https://github.com/TrinityCore/TrinityCore/pull/30173](https://github.com/TrinityCore/TrinityCore/pull/30173)

**Comment by motivewc** [comment]
macOS support is now in Trinity. :)
